---
title: "ES102 | Aug-Nov 2023"
sidebar: false
toc: false
css: ../../../css/teaching.css
listing:
  - id: lectures-listing
    contents: materials.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials.ejs
  - id: assignments-listing
    contents: materials-assignments.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
    field-types: 
      dateissued: date
      due: date
  - id: quizzes-listing
    contents: materials-quizzes.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
    field-types: 
      dateissued: date
      due: date
  - id: exams-listing
    contents: materials-exams.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
date-format: DD MMM, YYYY
---


:::{.column-body-outset}

## ES102. <COURSE TITLE>

##### 2020


:::{.callout-note collapse="true" icon="false"}

##### About the Course

Course summary.

:::
:::{.callout-note collapse="true" icon="false"}

##### Target Audience

Information about target audience.

:::

:::{.callout-tip collapse="true" icon="false"}

##### Prerequisites

Indication of pre-requisites.

:::

:::{.callout-tip collapse="true" icon="false"}

##### References

List of References

:::
:::{.callout-caution collapse="true" icon="false"}

##### Timings and Venue

Venue: XYZ

Timings:

:::
:::{.callout-caution collapse="true" icon="false"}

##### TAs and Office hours

Office Hours: By email.

TAs:

List of TAs.

:::

:::{.callout-important collapse="true" icon="false"}

##### Evaluation policy

- Each of the three exams account for 20% of the grade.
- Each of the eleven tutorials will have a quiz worth 5 points. The total number of points you can earn through quizzes is capped at 40, and accounts for 40% of the grade.
- There will be weekly assignments that are not graded but are recommended for practice. 

:::

:::{.callout-important collapse="true" icon="false"}

##### Logistics

- For IITGN students, (pre-)register through IMS as usual. 
- All quizzes and exams will be on Mathmatize; please [sign up here](https://mathmatize.com/c/809).
- For announcements, please sign up on Google classroom [with this link](https://classroom.google.com/c/NjE3MjAzOTUzMTA0?cjc=nzl3hkr) or use the invite code **nzl3hkr**.
- If you are not from IITGN and are interested in taking up the course, then please send us an email.

:::

::: {.panel-tabset}

## Lectures

All slides for the initial lectures can be found [here](https://slides.com/neeldhara/ES102-2023).

::: {#lectures-listing}
:::


## Assignments

::: {#assignments-listing}
:::

## Quizzes

::: {#quizzes-listing}
:::

## Exams

::: {#exams-listing}
:::

:::

:::


