---
draft: true
---

I've gotten a lot of well-meaning advice about going out more (e.g, a postdoc abroad, etc.). Turns out, this simply wasn't feasible for me by and large.

With friends who had broader experiences, I had some first-order approximations of what I was missing out on.

For as long as I can remember, I turned to YouTube and podcasts to compensate: for an introvert, being a fly on the wall who didn't have to engage worked out perfectly!

If not actual intel, I felt I caught enough of the vibe of places I couldn't be, so I largely avoided FOMO.

I've never been particularly comfortable on social media, and I can't remember how or when Twitter became an exception. 

So color me amused by this FT column suggesting that the real reason to leave Twitter is that it's... too comfortable?

https://twitter.com/JohnRentoul/status/1591355838299799555?s=20&t=nesxsAEMs_n4K9Se8XvjtQ

It has, indeed, been a comfortable hangout for me: and surprisingly so, considering the nastiness it's known for. 

I've taken my chances here and it's largely been very fun, and I daresay my time here has influenced the way I think about many things, for better or worse.

That said, I suppose I do have my own "real reasons" for planning to move on. It's just... not the comfort 😀

https://twitter.com/neeldhara/status/1590210797220687872?s=20&t=r1RjVgIzZBGBAg9c1HwyYA