---
title: "33 Miniatures | Winter 2023"
sidebar: false
toc: false
css: ../../../css/teaching.css
listing:
  - id: youtube-listing
    contents: youtube.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: materials.ejs
date-format: DD MMM, YYYY
---


:::{.column-body-outset}

## Reading Group on 33 Miniatures in Linear Algebra

##### Winter 2023 (Nov/Dec)

:::{.callout-note collapse="true" icon="false"}

##### About the Course

This is a reading group for the book [Thirty-three Miniatures: Mathematical and Algorithmic Applications of Linear Algebra](https://kam.mff.cuni.cz/~matousek/stml-53-matousek-1.pdf) that will be active between 1st November to 10th December.


:::
:::{.callout-note collapse="true" icon="false"}

##### Target Audience
You will find this course interesting if

- you have some background in linear algebra
- you enjoyed the linear algebra you have seen
- you are curious about linear algebraic concepts can be useful in contexts of combinatorics, geometry, and algorithms.

If you have not formally studied linear algebra before and have been looking for an excuse to pick it up, then that should be a good use-case too!

:::

:::{.callout-tip collapse="true" icon="false"}

##### Prerequisites
A little linear algerba won't hurt. Try starting here if you have never encountered linear algebra concepts before:

1. [The Linear Algebra course on Khan Academy](https://www.khanacademy.org/math/linear-algebra)
2. [The 3blue1brown Playlist](https://www.youtube.com/watch?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&v=fNk_zzaMoSs&embeds_referring_euri=https://linearalgebra33.discourse.group/&source_ve_path=MjM4NTE) on the "Essence of Linear Algebra"
3. [An interactive introduction](https://brilliant.org/landing/interactive-courses-learn-linear-algebra/) from Brilliant.

:::

:::{.callout-tip collapse="true" icon="false"}

##### References

We will closely follow [Thirty-three Miniatures: Mathematical and Algorithmic Applications of Linear Algebra](https://kam.mff.cuni.cz/~matousek/stml-53-matousek-1.pdf). Additional pointers to tangents and related material will be listed on the individual notes pages.

:::

:::{.callout-tip collapse="true" icon="false"}

##### Materials

1. [All Slides](https://slides.com/neeldhara/33-miniatures) (online, work in progress)
2. [Dropbox Folder with PDF exports](https://www.dropbox.com/scl/fo/k9p7xnue7jm0uvo4b21sp/h?rlkey=e7ekygx1qeixy24wxmit2xlqy&dl=0) (updated sporadically, but should be fully up to date by the end of the course)
3. [Youtube Playlist](https://www.youtube.com/playlist?list=PLadhlDF3zdvv81kngHfUoFR6n1iMj-7vk) (updated daily)
4. [Discourse Community](https://linearalgebra33.discourse.group/c/33-miniatures/) (for pointers emerging from discussions)
5. Miniature-wise notes and discussion pages linked to below

:::
:::{.callout-caution collapse="true" icon="false"}

##### Timings and Venue

(03/12) The reading group meetings have concluded (for now). We met at 10PM IST on all days during November, with three skips (one for Diwali, one for the CWC finals, and one because of technical issues). So we met for the first two days of December too, clocking in 29 total sessions, 26-ish hours, and 28 miniatures (two of them took two days, and we once covered two miniatures in one session). We tentatively plan to do a week-long reunion meet in January some time to discuss the five remaining miniatures (#28, #29, #31, #32, #33). The forum will remain open until then: please feel free to discuss while we take a break from the daily meetings!

(01/11) We meet at 10PM IST. Join [via Zoom](https://iitgn-ac-in.zoom.us/j/92083656199?pwd=OGRuU2pyV2RSTGhLYnFjRklWQy9GZz09) (code: matousek) and/or check out [the slides](https://slides.com/neeldhara/33-miniatures) here. Here's a [Google Calendar](https://calendar.google.com/calendar/u/0?cid=MWRiYzZmNzNkYWFiZDI5YmFlOTVlYzRmMjVmYTZkZjgwMWVhZDFiOTE3MGY5ODJiMTNkMmY1OTlkMTI4NmVhNUBncm91cC5jYWxlbmRhci5nb29nbGUuY29t) that you can subscribe to (simplest if you are already logged into gmail), or [a link to download an ICS file](https://calendar.google.com/calendar/ical/1dbc6f73daabd29bae95ec4f25fa6df801ead1b9170f982b13d2f599d1286ea5%40group.calendar.google.com/public/basic.ics) (easier if you are not on gmail but want to add the events to your calendar app). 

:::

---

:::{.callout-tip appearance="minimal"}
_Acknowledgements._ Special thanks to [Vinay](https://twitter.com/ainvvy) for a lot of guidance with these sessions, and for all the insights during the discussions! Many thanks to all the participants for being there: this was very motivating for me, and it was a lot of fun doing this collectively :) Also, I owe one to [Saket](https://www.imsc.res.in/saket_saurabh) for introducing me to these miniatures when I was in grad school!
:::

:::{.callout-note appearance="minimal"}
_Tools._ In no particular order:

- I used [Slides](https://www.slides.com/), a very helpful UI on top of the [revealjs](https://revealjs.com/) framework, to make these slides. 
- As is perhaps quite apparent, I borrowed heavily from the miniatures themselves, and [mathpix](https://mathpix.com/) made that easy to do. 
- The font I use everywhere (in particular, also on the slides) is [Heliotrope](https://mbtype.com/fonts/heliotrope/) by [Matthew Butterick](https://matthewbutterick.com/). 
- Some of the content on the slides (typically example matrices) were generated by [Copilot](https://copilot.microsoft.com/)]. 
- Some content was generated using [Polypad by Mathigon](https://mathigon.org/polypad) and [Geogebra](https://www.geogebra.org/).
- The discussions are hosted on [Discourse](https://www.discourse.org/), who offer a education discount on their hosted plans, and they were also very supportive in responding to all my setup-related inquiries! 
- This webpage is powered by [Quarto](https://quarto.org/docs/websites/). 
- The meetings were hosted on Zoom, on a IITGN-provided account. 
:::

:::{.callout-important appearance="minimal"}
_Discussions._ If you are interested in discussions around these topics, please join our [limited-edition online Discourse community](https://linearalgebra33.discourse.group/c/33-miniatures/)! You don't need to login if you just want to read the posts, but perks of creating an account include:

1. Daily email reminders
2. The ability to react and respond to posts

Please note that the community will only remain active until ~end of January 2024, and will be archived thereafter. A static copy of the contents will be made available on a best-effort basis.
:::

---

::: {#youtube-listing}
:::

:::