---
title: "Windmill"
date: "2022-10-14"
categories: [geometry]
fields: [date, title]
css: /css/tgif.css
toc: true
---

Source: [IMO 2011, C3](https://www.imo-official.org/problems/IMO2011SL.pdf)

:::{.callout-note appearance="minimal"}
A hard puzzle with a beautiful solution.
:::

##### The Problem

> Let $\mathcal{S}$ be a finite set of at least two points in the plane. Assume that no three points of $\mathcal{S}$ are collinear. By a windmill we mean a process as follows. Start with a line $\ell$ going through a point $P \in \mathcal{S}$. Rotate $\ell$ clockwise around the pivot $P$ until the line contains another point $Q$ of $\mathcal{S}$. The point $Q$ now takes over as the new pivot. This process continues indefinitely, with the pivot always being a point from $\mathcal{S}$.
>
> Show that for a suitable $P \in \mathcal{S}$ and a suitable starting line $\ell$ containing $P$, the resulting windmill will visit each point of $\mathcal{S}$ as a pivot infinitely often.

{{< bi exclamation-triangle-fill >}} Spoiler: a neat 3blue1brown [video](https://youtu.be/M64HUIJFTZM) and [lesson](https://youtu.be/M64HUIJFTZM) on the solution.