---
title: Cards and Combinatorics | Manish Jain
css: /css/teaching.css
sidebar: false
toc: false
---

## Cards and Combinatorics
##### A Short Course

--- _Manish Jain_

:::{.callout-note collapse="true" icon="false"}

# About the Course

In this course, we will introduce many little-known theorems of advanced mathematics. We will go on a roller coaster ride from delightful self-working magic tricks to serious math, then back again to magic. The tricks don’t require any sleight of hand or trickery.
 
A similar course is taught at Stanford University by a former professional magician named Persi Diaconis. At school, Diaconis supported himself by playing poker on ships between New York and South America. Martin Gardner, a writer at Scientific American, once saw him and recommended to a professor for Ph.D. at Harvard University.
 
In two days, we would learn about Hummer shuffles, Royal Hummer, de Bruijn Sequences, Universal Cycles, Mandelbrot Set, Neat Shuffles and many more card tricks. You would have about 10 cool card tricks up your sleeve and you would be comfortable exploring many more as you would know the terminology of math card tricks by the end of the course.
 
:::

:::{.callout-note collapse="true" icon="false"}
# About the Instructor

Manish Jain spends most of his time investigating the science behind simple toys, and is passionate about sharing his insights and excitement with people. He is Associate Teaching Professor at Center for Creative Learning (CCL), IIT Gandhinagar, whose goal is to create and foster makers who can take innovation to the next level. Towards this goal, CCL designs and offers deep and joyful learning experiences built around STEM toys and hands-on activities. The ultimate goal is to bring back the gleam in the eyes of students and teachers.
 
Before founding CCL, Manish worked at IUCAA’s Science Centre in Pune, with Padma Shri Arvind Gupta. In his previous avatar, he spent 19 years in the area of chip design at Synopsys (Bangalore & amp; Mountain View), serving as a Director of R&D and Scientist leading Low Power Simulation efforts, where he has 5 US patents.
 
Manish has a bachelor’s degree in Electrical Engineering from IIT Kanpur (1993) and has also finished a few courses at Stanford University.
 

:::


:::{.callout-note collapse="true" icon="false"}
# Dates and Time

6th and 7st April, 2019 • 10:00 AM to 1:00 PM, 3:00 PM to 5:00 PM

:::




