---
css: /css/teaching.css
toc: false
sidebar: false
title: CS614. Advanced Algorithms. L02 Quiz.
code-copy: true
---

:::{.column-body-outset}

## CS614. Advanced Algorithms. 

##### L02 Quiz

[Back to the course page](../index.qmd)



:::{.callout-note icon="false"}

# Problem 1. Identify the Circuits

Let $G$ be a simple, undirected, and connected graph. Consider the graphic matroid discussed in class, i.e, where:

- the universe $U$ is the set of _edges_ of $G$, i.e, $E(G)$; 
- the family $\mathcal{F}$ of independent sets is the collection of all subsets of edges that are acyclic.

A _maximal_ independent set in a matroid is called a basis, and for this example, the maximal independent sets correspond to spanning trees.

A _minimal_ dependent set in a matroid is called a circuit. In this example, what are the circuits?

:::


:::{.callout-note icon="false"}

# Problem 2. Matchings

Let $G$ be a simple, undirected, and connected graph. Consider the following set system:

- the universe $U$ is the set of _edges_ of $G$, i.e, $E(G)$; 
- the family $\mathcal{F}$ of independent sets is the collection of all subsets of edges that are matchings.

Is this a matroid? Why or why not? Justify your answer.

:::


:::{.callout-note icon="false"}

# Problem 3. Independent Sets

Let $G$ be a simple, undirected, and connected graph. Consider the following set system:

- the universe $U$ is the set of _vertices_ of $G$, i.e, $V(G)$; 
- the family $\mathcal{F}$ of independent sets is the collection of all subsets $S$ of that are independent in $G$, i.e, the subgraph $G[S]$ has no edges.

Is this a matroid? Why or why not? Justify your answer.

:::


:::