---
title: "On Career Choices"
date: "2023-05-26"
categories: [funda]
fields: [date, title]
toc: true
---

:::{.callout-tip appearance="simple" icon="false"}
A version of this article was featured in _A Lesson from IIT_, a column on the Indian Express. The link to the column is [here](https://indianexpress.com/about/a-lesson-from-iit/), and [this](https://indianexpress.com/article/education/a-lesson-from-iit-how-do-you-figure-out-your-interest-if-engineering-is-right-choice-iit-gandhinagar-jee-main-jee-advanced-2023-8629639/) is the link to the present article. Many thanks to [Ritika Chopra](https://indianexpress.com/profile/author/ritika-chopra/) for prompting me to write this, and for not giving up on me as I took my time :)

Thanks are also due to friends Manasa, Jyothi, and Sharmistha for going over early versions of this writeup and sharing their thoughts!
::: 

During school, my earliest exposure to the notion of being an engineer was an at-the-time popular audio clip called the knack, in which a doctor is diagnosing a kid with a condition involving extreme intuition for all things mechanical and electrical. It is implied that having the knack is not compatible with a normal life, since the kid is now destined to “be an engineer”. This causes his mother to experience much concern and grief. This inspired me to keep a polite but firm distance from all things engineering, conveniently including the entrance exams meant to unlock the gates of the IITs.

College admissions are rife with two types of scenarios that are less than ideal: students ending up in programs that are not their cup of tea, and students missing out on experiences that would have been right up their alley. These mismatches are cumulatively expensive: there is the price paid in misallocated resources, and then there’s the personal cost of training for programs that eventually turn out to be a poor fit, which is typically very substantial.

Some of this can be mitigated with an appreciation of what these programs entail, and what the campuses have to offer. The IITs are known predominantly for their undergraduate programs in the traditional engineering disciplines. However, several of them also host excellent programs in the sciences. Further, there are an increasing number of undergraduate programs that have interdisciplinary themes (such as the Btech program in [Civil and Infrastructure Engineering with specialization in Smart Infrastructure](https://iitj.ac.in/department/index.php?id=ug_program&dept=civil) at IIT Jodhpur) and a focus on emerging technologies and areas (for instance, the BTech program in [Artificial Intelligence](https://ai.iith.ac.in/programs/btech.html) at IIT Hyderabad or the undergraduate program in [Design](https://twitter.com/iitdelhi/status/1574782831221698562) at IIT Delhi).

Currently, awareness about these opportunities is mostly a heady mix of word of mouth, Quora answers, vibes from coffee-table conversations at coaching centers, and placement statistics on popular media. Impressions of what campus life entails is also largely a combination of imagination fueled by things seen on, say, Netflix and the like. However, if you are a prospective student or a parent of one, you would do well to go beyond these secondary sources of intelligence and get some first-hand experience.

Most IITs host open days every so often: these are special days when the campuses are open to anyone to walk in, and professors and students from the organization delight in sharing what they are up to with accessible demonstrations or lab tours. A recent example is the [G20-Ignite Sci-Tech fair](https://students.iitgn.ac.in/ignite) which hosted hundreds of school students at the IIT Gandhinagar campus. Often, even one such experience can trigger an inner calling, helping you identify the thing you want to do for life – or at least for a substantial duration. 

You could also go beyond the glimpses offered by open days. Watch out for opportunities to collaborate over small projects. For example, the [Center for Creative Learning at IIT Gandhinagar](https://ccl.iitgn.ac.in/) welcomes high school students for short term projects over summer, and students who do well in courses on the [NPTEL](https://nptel.ac.in/) platform have a shot at internships with the instructors of those courses. Many professors delight in talking to students: check out the various seasons of [Talk to a Scientist](https://www.talktoascientistindia.com/home), for example. You can also ask your school to reach out to professors at nearby institutions for an interactive session, or approach organizations like [INYAS](https://inyas.in/) that focus deeply on outreach activities at the school level. Finally, several IITs also host bootcamps, hackathons, and so on: they are usually announced on their websites and social media channels, so keep an eye out for these!

Having said all this, a choice of career – or more immediately, a branch or stream – does not have to be prompted necessarily by an intense love at first sight. The routes leading to your final pursuit(s) can be potentially meandering, and not having an inner voice abundant in clarity should be no cause for alarm. Examples of this abound, and I’ll share a representative one. [Ronald Graham](https://en.wikipedia.org/wiki/Ronald_Graham) is arguably best-known as an American mathematician who made fundamental contributions to combinatorics. Because his father worked in various jobs related to oil fields and shipbuilding, he moved schools often. He did not study in any school for more than eighteen months and often studied in grades higher than what would have been normal for his age.

At the age of 15, Graham won a Ford Foundation scholarship to the University of Chicago, where he spent three years learning gymnastics. Because of his outstanding performance in math on the scholarship examinations, he did not (have to) take any mathematics courses. After the duration of the scholarship, he moved to the University of California at Berkeley, where he majored in electrical engineering. During this time, a one-off number theory course with D H Lehmer “fired his imagination for the subject”. After four subsequent years in the Air Force, during which he also earned a B.S. in physics, he returned to UC Berkeley where he completed his Ph.D. in mathematics with D H Lehmer as his thesis advisor. 

All this is to say that life can be — and typically is — highly non-linear. I would argue that as much as we like to imagine being in control, planning one’s future down to summer-vacation-wise bucket lists is perhaps somewhat excessive. Your first branch and your first job does not have to be your last: for more evidence, I recommend reading Tim Ferriss’ book, [Tribe of Mentors](https://www.amazon.in/Tribe-Mentors-Short-Advice-World/dp/1328994961). Now, you might be prone to making your choices after optimizing for a dozen variables or more, or you might prefer leaving your destiny to the gods of randomness. I believe somewhere in between, there is an approach more reasonable than either extreme: make an informed choice after investing a finite amount of your own time and energy into understanding what actually lies in store.

The IITs are now far from being the only ticket to the good life and a powerful alumni network: if these are your main motivators, you might consider exploring less painful pathways to the same outcomes. If not, allow yourself the space to let your instincts come to the fore, and follow them to make your choices. This will maximize the chances that you will end up in a meaningful journey that involves truly enjoying what the programs have to offer, instead of being in a situation where you have simply transitioned from one rat race into another.

