---
title: "Iwahiro's Square in Bag Puzzle"
date: "2022-10-07"
categories: [folding, paper]
fields: [date, title]
css: /css/tgif.css
toc: true
---

:::{.callout-tip appearance="simple" icon=false}
Source: Dave Richeson [@divbyzero](https://twitter.com/divbyzero).
:::

Here's a very fun packing puzzle.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">One of my all-time favorite puzzles: Iwahiro&#39;s &quot;Square in a Bag&quot; puzzle. Put a square piece of paper (14 cm x 14 cm) completely inside a bag (20 cm x 11 cm) without folding, cutting, or rolling up the paper; it should end up lying completely flat. <a href="https://t.co/nGv2TwR8Wp">pic.twitter.com/nGv2TwR8Wp</a></p>&mdash; Dave Richeson (@divbyzero) <a href="https://twitter.com/divbyzero/status/1577308868476108806?ref_src=twsrc%5Etfw">October 4, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

When we discussed this in the meetup, it was a little hard to describe what's allowed and what's not with the _bag_. Another thing that was important to emphasize is the side of the bag that is open: I am not sure this is even possible if the bag is sealed on both the long sides and only the short side is the one that is open.

A quick sanity check with respect to surface areas reassures us of the potential feasibility of the task: the total surface area of the square is indeed smaller than the surface area of the bag. So if you imagine cutting the bag along the short sides, and using it as a gift wrap to cover up the square, that's very much doable.

The other hint was the fact that the length of the diagonal of the square is less than the length of the longer side of the bag. This prompts us to line up the square so that it's opposite corners align with the long and open edge of the bag.

:::{.callout-caution collapse="true" icon=false}
## Spoiler Alert
The solution does indeed involve starting here and squishing the bag gradually so that it engulfs the square. Here's a nice video demonstration:

<iframe width="560" height="315" src="https://www.youtube.com/embed/SACE14qPVo0?start=80" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
:::

We did wonder about formalizing the question and the process above a little more, but we were not able to come up with any appropriate language. At least as an activity-based puzzle I think the instructions are quite clear:

<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">Ah. The bag can stretch and fold as much as any ordinary kitchen bag can. And for that matter, the paper can warp and bend as you&#39;d expect it would. But in the end everything will end up flat on the tabletop.</p>&mdash; Dave Richeson (@divbyzero) <a href="https://twitter.com/divbyzero/status/1578482477869715457?ref_src=twsrc%5Etfw">October 7, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

It would be nice to be come up with a procedure that, given the dimensions of the square and the bag, can determine if the square can in fact be accommodated in the bag playing by the rules here. Already here, it was pointed out later that it would have worked with [a slightly smaller bag too](https://twitter.com/divbyzero/status/1577322638783004675?s=20&t=346fCpYPw5ZtAIAQJZ-PtA), and at least for the purpose of getting to this particular solution, all that matters is the [proportions of the side lengths](https://twitter.com/divbyzero/status/1577322638783004675?s=20&t=346fCpYPw5ZtAIAQJZ-PtA).

It might also be interesting to think about what happens with other combinations of shapes.