---
title: "1000 bottles of wine"
date: "2023-11-23"
categories: [card]
fields: [date, title]
css: /css/tgif.css
toc: true
---

Source(s): folklore puzzle, proposed by [Manoj](http://people.iitgn.ac.in/~gmanoj/) during the 16 Sep 2023 puzzle group meetup at IITGN.

The text below is borrowed from [Brett Berry's blog](https://medium.com/i-math/math-as-mental-weightlifting-and-a-king-s-dilemma-58fa2bfd2660).


##### The Problem

> The King of a small country invites 1000 senators to his annual party. As a tradition, each senator brings the King a bottle of wine. Soon after, the Queen discovers that one of the senators is trying to assassinate the King by giving him a bottle of poisoned wine. Unfortunately, they do not know which senator, nor which bottle of wine is poisoned, and the poison is completely indiscernible. 

> However, the King has 10 prisoners he plans to execute. He decides to use them as taste testers to determine which bottle of wine contains the poison. The poison when taken has no effect on the prisoner until exactly 24 hours later when the infected prisoner suddenly dies. The King needs to determine which bottle of wine is poisoned by tomorrow so that the festivities can continue as planned. Hence he only has time for one round of testing. How can the King administer the wine to the prisoners to ensure that 24 hours from now he is guaranteed to have found the poisoned wine bottle?


:::{.callout-note appearance="minimal" collapse="true"}
## {{< bi exclamation-triangle-fill >}} Spoiler
Label each bottle with both its decimal number and binary equivalent, and have the prisoners drink from said bottle according to the binary code: for example, if a bottle is labeled 0011010101, then have prisoners C, D, F, H and J drink from it. If the bottle is poisoned, then the prisoners who drank from it will die 24 hours later, and the King will know which bottle it was.
:::

