---
title: "Women in Mathematics"
date: "2022-02-21"
categories: [books, list]
fields: [date, title]
toc: true
---

Here’s a list of books — in no particular order — about women in mathematics (broadly interpreted) largely taken from [this thread](https://twitter.com/stevenstrogatz/status/1495030448904458243). The links are mostly to versions of the books on Amazon India. Unfortunately many of them are rather expensive, but hopefully it’s a handy list to share with a librarian you know! Do leave a comment below if you have any additions.

I’ll also leave this [relatively sobering thought](https://twitter.com/virtualcourtney/status/1495076053257175040) (or [this one](https://twitter.com/MarissaKawehi/status/1495083281766879243?s=20&t=9CWcnFgcqBQZD4p01UFXsg)) here with no further comment.

---

Books:

1. [Complexities – Women in Mathematics](https://www.amazon.in/Complexities-Mathematics-Bettye-Anne-Case/dp/0691114625/)

2. [Women in Mathematics – The Addition of Difference](https://www.amazon.in/Women-Mathematics-Addition-Difference-Science/dp/0253211190/ref=sr_1_1?crid=XLR5PKP93HN1&keywords=Women+in+Mathematics%3A+The+Addition+of+Difference&qid=1645384438&sprefix=women+in+mathematics+the+addition+of+difference%2Caps%2C277&sr=8-1)

3. [How to Free Your Inner Mathematician: Notes on Mathematics and Life](https://www.amazon.in/How-Free-Your-Inner-Mathematician/dp/0198843593/)

4. [Ada's Algorithm: How Lord Byron's Daughter Launched the Digital Age Through the Poetry of Numbers](https://www.amazon.in/Adas-Algorithm-Daughter-Launched-Digital/dp/1783340711/)

5. [Women Who Count: Honoring African American Women Mathematicians](https://www.amazon.in/Women-Who-Count-Honoring-Mathematicians/dp/1470448890/)

6. [Women Becoming Mathematicians – Creating a Professional Identity in Post–World War II America](https://www.amazon.in/Women-Becoming-Mathematicians-Professional-Post-World/dp/0262632462/)

7. [Power in Numbers: The Rebel Women of Mathematics](https://www.amazon.in/Power-Numbers-Rebel-Women-Mathematics/dp/1631064851/)

8. [My Remarkable Journey: A Memoir](https://www.amazon.in/My-Remarkable-Journey-Katherine-Johnson/dp/0062897667/) (Katherine Johnson)

9. [Proving It Her Way: Emmy Noether, a Life in Mathematics](https://www.amazon.in/Proving-Her-Way-Noether-Mathematics/dp/3030628108/)

10. [Emmy Noether’s Wonderful Theorem](https://www.amazon.in/Emmy-Noether%60s-Wonderful-Theorem-2e/dp/1421422670/)

11. [Love and Mathematics: Sofya Kovalevskaya](https://www.amazon.in/Love-Mathematics-Kovalevskaya-P-Kochina/dp/0828533733/) ([alternate link](https://archive.org/details/kochinaloveandmathematicssofyakovalevskaya1985/mode/2up))

12. [Einstein's Wife: The Real Story of Mileva Einstein-Maric](https://www.amazon.in/Einsteins-Wife-Story-Mileva-Einstein-Maric/dp/1665124997)

13. [Inventing the Mathematician: Gender, Race, and Our Cultural Understanding of Mathematics](https://www.amazon.in/Inventing-Mathematician-Cultural-Understanding-Mathematics-ebook/dp/B01CPUKOR6/)

14. [In Code: A Mathematical Journey](https://www.amazon.in/Code-Mathematical-Journey-David-Flannery/dp/1861972717)

15. [Against All Odds: Women’s Ways to Mathematical Research Since 1800: 6 (Women in the History of Philosophy and Sciences)](https://www.amazon.in/Against-All-Odds-Mathematical-Philosophy/dp/303047612X)

16. [The Ascent of Mary Somerville in 19th Century Society](https://www.amazon.in/Somerville-Century-Society-Springer-Biographies-ebook/dp/B01N1M5D2H/)

17. [Julia: A Life in Mathematics](https://bookstore.ams.org/spec-18/) (ebook only)

18. [Women of Mathematics: A Bio-Bibliographic Sourcebook](https://www.amazon.in/Women-Mathematics-Bio-Bibliographic-Sourcebook-Bibliographic-ebook/dp/B000WBBEIE/)

19. [A Celebration of the EDGE Program's Impact on the Mathematics Community and Beyond](https://www.amazon.in/Celebration-Programs-Impact-Mathematics-Community/dp/3030194884/)

20. [Those Magnificent Women and their Flying Machines: ISRO'S Mission to Mars](https://www.amazon.in/Those-Magnificent-Women-Flying-Machines/dp/9388874587)

21. [Girls Coming to Tech!: A History of American Engineering Education for Women](https://www.amazon.in/Girls-Coming-Tech-Engineering-Education-ebook/dp/B08BTB9HQ2/)

22. [Fifty Years of Women in Mathematics](https://link.springer.com/book/9783030826574)

23. [x+y: A Mathematician's Manifesto for Rethinking Gender](https://www.amazon.in/Mathematicians-Manifesto-Rethinking-Gender/dp/178816041X/)


Illustrated Books:

1. [Maryam’s Magic: The Story of Mathematician Maryam Mirzakhani](https://www.amazon.in/Maryams-Magic-Mathematician-Maryam-Mirzakhani/dp/0062915967/)

2. [Nothing Stopped Sophie: The Story of Unshakable Mathematician Sophie Germain](https://www.amazon.in/Nothing-Stopped-Sophie-Cheryl-Bardoe/dp/0316278203/)

3. [Grace Hopper: Queen of Computer Code](https://www.amazon.in/Grace-Hopper-Queen-Computer-Changed/dp/1454920009/)

4. [Ada Byron Lovelace and the Thinking Machine](https://www.amazon.in/Ada-Byron-Lovelace-Thinking-Machine/dp/1939547202)

5. [The Thrilling Adventures of Lovelace and Babbage: The (Mostly) True Story of the First Computer](https://www.amazon.in/Thrilling-Adventures-Lovelace-Babbage-Computer/dp/0141981539/)

6. [The Girl With a Mind for Math: The Story of Raye Montague](https://www.amazon.in/Girl-Mind-Math-Montague-Scientists/dp/1943147426/)

7. [Hidden Figures: The True Story of Four Black Women and the Space Race](https://www.amazon.in/Hidden-Figures-Story-Black-Women/dp/0062742469/)

8. [Counting on Katherine: How Katherine Johnson Put Astronauts on the Moon](https://www.amazon.in/Counting-Katherine-Johnson-Astronauts-Moon/dp/1529005612/)

9. [Emmy Noether: The Most Important Mathematician You've Never Heard Of](https://www.amazon.in/Emmy-Noether-Important-Mathematician-Youve-ebook/dp/B08J87C17B)


Miscellaneous:

1. [A Tribute to Professor Helena Rasiowa](http://comet.lehman.cuny.edu/fitting/bookspapers/pdf/papers/Rasiowa.pdf) (PDF)

2. [A Groundbreaking Mathematician on the Gender Politics of Her Field](https://www.newyorker.com/news/q-and-a/groundbreaking-mathematician-karen-uhlenbeck-on-the-politics-of-her-field/amp) (New Yorker)