---
date-format: DD MMM, YYYY
date: 26 11 2023
discourse: ''
notes: 19/
slides: null
summary: ''
title: '#19. The End of the Small Coins'
---

(Back to [course page](../).)

[Link to Slides ](https://slides.com/neeldhara/33-miniatures#/19) · [Link to recording](https://www.youtube.com/watch?v=908Km0MS78c&list=PLadhlDF3zdvv81kngHfUoFR6n1iMj-7vk&index=19)

---

Prompts for discussion:

Recall that this was the main result:

> If at most \(t\) pieces of each product have been ordered in total, and if no order asks for more than one piece of each product, then it is possible to round the prices so that the total price of each order changes by no more than \(t\) Euros.

One interesting aspect of this is that the change in price is independent of the total number of orders and the number of different products (also pointed out in the miniature). However, we do pay a price for this coolness: the two assumptions about the frequency of orders and the fact that we are restricted to each order having at most one piece of each product. What happens if you relax either/both assumptions? Can we meaningfully extend the result to accommodate more scenarios (e.g, no order asks for more than $d$ pieces of each product)? Can we design examples that justify the assumptions?

Another discrepancy-inspired puzzle is covered in this [Numberphile video](https://www.youtube.com/watch?v=pFHsrCNtJu4).