---
title: "ES 214 | Aug-Nov 2023"
sidebar: false
toc: false
css: ../../../css/teaching.css
listing:
  - id: lectures-listing
    contents: materials.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials.ejs
  - id: exams-listing
    contents: materials-exams.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
date-format: DD MMM, YYYY
---


:::{.column-body-outset}

## ES214. Discrete Mathematics

##### August --- November 2023

(co-instructor with [Prof. Anirban Dasgupta](https://sites.google.com/site/anirbandasgupta).)

:::{.callout-note collapse="true" icon="false"}

##### About the Course

This is a first course in discrete mathematics and has a broad scope: we introduce elementary concepts in logic, set theory, combinatorics, graph theory, number theory, and probability. The course is designed to be accessible to students from all disciplines, and is a core course for the B.Tech. program at IITGN. We hope that students taking this course discover the beauty of mathematical methods and their applications. 

:::
:::{.callout-note collapse="true" icon="false"}

##### Target Audience
You will find this course interesting if:

- you think counting the number of ways in which you can complete your graduation requirements is a fun problem to think about,
- you enjoy logic puzzles [like this one](https://www.youtube.com/watch?v=LKvjIsyYng8) or probability puzzles [like this one](https://www.youtube.com/watch?v=6_yU9eJ0NxA), or
- you like [box-stacking challenges](https://en.wikipedia.org/wiki/Instant_Insanity), or
- you are enrolled in a program for which this course is in the core.

:::

:::{.callout-tip collapse="true" icon="false"}

##### Prerequisites
This course is self-contained and involves no pre-requisites.
:::

:::{.callout-tip collapse="true" icon="false"}

##### References

1. [Discrete Mathematics and Its Applications](https://www.mheducation.com/highered/product/discrete-mathematics-applications-rosen/M9781259676512.html) by Kenneth Rosen
2. [Open Textbook on Discrete Mathematics](https://open.umn.edu/opentextbooks/textbooks/discrete-mathematics-an-open-introduction)
3. [Proofs: A Long-Form Mathematics Textbook](https://longformmath.com/proofs-home) by Jay Cummings
4. [Playing with Discrete Math](http://kyleburke.info/CGTBook.php) by Kyle Burke and Craig Tennenhouse
5. Online Course (with lecture videos): [Math 4190, Summer I 2019](http://www.math.clemson.edu/~macaule/classes/m19_math4190/)

:::
:::{.callout-caution collapse="true" icon="false"}

##### Timings and Venue

Venue: 1/101

Lectures:

- Tuesdays 3:30PM --- 5:00PM
- Wednesdays 11:30 --- 12:50

Tutorials 

- Thursdays 3:30PM --- 5:00PM 

:::
:::{.callout-caution collapse="true" icon="false"}

##### TAs and Office hours
Office Hours: By email.

TAs:

1. Harshil Mittal
2. Saraswati Nanoti
3. Eshwar Dhande 

:::

:::{.callout-important collapse="true" icon="false"}

##### Evaluation policy
- Each of the three exams account for 20% of the grade.
- Each of the eleven tutorials will have a quiz worth 5 points. The total number of points you can earn through quizzes is capped at 40, and accounts for 40% of the grade.
- There will be weekly assignments that are not graded but are recommended for practice. 
:::

:::{.callout-important collapse="true" icon="false"}

##### Register

- For IITGN students, (pre-)register through IMS as usual. 
- All quizzes and exams will be on Mathmatize; please [sign up here](https://mathmatize.com/c/809).
- For announcements, please sign up on Google classroom [with this link](https://classroom.google.com/c/NjE3MjAzOTUzMTA0?cjc=nzl3hkr) or use the invite code **nzl3hkr**.
- If you are not from IITGN and are interested in taking up the course, then please send us an email.

:::

::: {.panel-tabset}
## Lectures

All slides for the initial lectures can be found [here](https://slides.com/neeldhara/es214-2023).

::: {#lectures-listing}
:::


## Assignments

<p>Weekly practice problems are posted to Google Classroom. There is no need to submit these assignments, but please make sure to get feedback from your peers, instructors and TAs as you go along. We also strongly encourage you to explore the problems from the courses available through Brilliant (access details have been shared on Google Classroom as well).</p>

<!-- ::: {#assignments-listing}
::: -->

## Quizzes

Problems and solutions for weekly quizzes are available from within Mathematize.
<!-- ::: {#quizzes-listing}
::: -->

## Exams

::: {#exams-listing}
:::

:::

:::


<!-- 
  - id: assignments-listing
    contents: materials-assignments.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
    field-types: 
      dateissued: date
      due: date
  - id: quizzes-listing
    contents: materials-quizzes.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
    field-types: 
      dateissued: date
      due: date
-->