---
title: "NPTEL | CS82 | Jan-Apr 2022"
sidebar: false
toc: false
css: /css/teaching.css
listing:
  - id: lectures-listing
    contents: materials.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials.ejs
  - id: assignments-listing
    contents: materials-assignments.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
    field-types: 
      dateissued: date
      due: date
  - id: exams-listing
    contents: materials-exams.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
date-format: DD MMM, YYYY
---


:::{.column-body-outset}

## CS614. Advanced Algorithms

##### January --- April 2023

:::{.callout-note collapse="true" icon="false"}

##### About the Course
This is a course on algorithm design with a focus on issues of modeling and implementation. Each lecture will be focused entirely on one or two problems that reveal the use of a specific algorithmic technique. The techniques themselves are chosen to be in line with those covered in existing NPTEL courses on data structures and algorithms, so that students who complete those courses can find in this course a natural follow up. 

:::
:::{.callout-note collapse="true" icon="false"}

##### Target Audience
This course is intended for anyone who wants to deepen their appreciation for algorithmic techniques that they have learned in a foundational course and/or would like to take a first step towards preparing for coding competitions such as the ICPC. 

:::
:::{.callout-tip collapse="true" icon="false"}

##### Prerequisites
This course assumes some background in the design and analysis of algorithm and a working familiarity with some programming language. Knowing C++ is useful but not required. 

:::
:::{.callout-tip collapse="true" icon="false"}

##### References

**Books.**

1. [Algorithms](http://algorithms.wtf/) by Jeff Erickson
2. [Open Data Structures](https://cdn.discordapp.com/attachments/857140787179552805/871729741957300234/Some_very_basic_introductory_notes_on_Algorithm_Design_and_Analysis_aimed_at_college_teachers_and_st.pdf) by Pat Morin
3. [Algorithms Illuminated](http://www.algorithmsilluminated.org/) by Tim Roughgarden
4. [Algorithm Design](https://www.cs.princeton.edu/~wayne/kleinberg-tardos/) by J. Kleinberg and E. Tardos
5. [Problem Solving with Algorithms and Data Structures using C++](https://runestone.academy/runestone/books/published/cppds/index.html) by Brad Miller, David Ranum, and Jan Pearce
6. [Problem Solving with Algorithms and Data Structures using Python](https://runestone.academy/runestone/books/published/pythonds3/index.html) by Brad Miller and David Ranum
7. [Think Data Structures](https://greenteapress.com/wp/think-data-structures/) by Allen B. Downey
8. [Some introductory notes on Design and Analysis of Algorithms](https://cdn.discordapp.com/attachments/857140787179552805/871729741957300234/Some_very_basic_introductory_notes_on_Algorithm_Design_and_Analysis_aimed_at_college_teachers_and_st.pdf) (PDF) by Venkatesh Raman
9. [Competitive Programming](https://cpbook.net/) (4th Edition) by Steven Halim, Felix Halim, and Suhendry Effendy
10. [Competitive Programmer’s Handbook](https://cses.fi/book/book.pdf) by Antti Laaksonen

---

**Other NPTEL Courses.** 

1. [DSA with Python](https://nptel.ac.in/courses/106/106/106106145/) by Madhavan Mukund 
2. [DSA](https://nptel.ac.in/courses/106/102/106102064/) by Naveen Garg

---

**YouTube Channels.** 

1. [Codechef](https://www.youtube.com/channel/UCh-5M0r0SBgb5xNCFXG7aXQ) 
2. [Errichto](https://www.youtube.com/channel/UCBr_Fu6q9iHYQCh13jmpbrg) 
3. [William Lin](https://www.youtube.com/channel/UCKuDLsO0Wwef53qdHPjbU2Q) 
4. [William Fiset](https://www.youtube.com/user/purpongie)

---

**Visualizations.** 

1. [Visualgo](https://visualgo.net/en) 
2. [OpenDSA](https://opendsa.org/)

---

**Blogs.** 

1. [Petr Mitrichev](https://petr-mitrichev.blogspot.com/)

:::
:::{.callout-caution collapse="true" icon="false"}

##### Timings and Venue
Lectures are pre-recorded. Any remote live sessions will be announced directly over email.

:::
:::{.callout-caution collapse="true" icon="false"}

##### TAs
TBA
:::
:::{.callout-important collapse="true" icon="false"}

##### Evaluation policy

If you have taken up this course through Swayam, then you would need to be formally enrolled in the course, and register for the certification exam to get a certificate of completion for the course. 

The grading policy is as follows.

- 12.5% of the final grade comes from the weekly quiz-based assignments. The best 8 out of 12 scores are considered.
- 12.5% of the final grade comes from the weekly programming assignments, where the weekly score is the average of the programming assignments every week. Again, only the best 8 out of 12 are considered.
- 75% of the final grade comes from the final exam, which is held at a physical location and whose format is similar to the weekly quizzes. Please note that there are *no* programming-based assessments in the final exam.


{{< bi exclamation-triangle-fill color="indianred" >}} _Important Note._ You will be eligible for a certificate only if average assignment score (quizzes and programming assignments combined) $\geq$ 10/25 and exam score $\geq$ 30/75. If one of the two criteria is not met, **you will not get the certificate** even if the final score is $\geq$ 40/100.


:::

:::{.callout-important collapse="true" icon="false"}

##### Register

Sign up for the course from [here](https://onlinecourses.nptel.ac.in/noc23_cs30/preview). **(Note: enrollment ends on 30 Jan 2023!)**

Also, you might find the following links useful:

1. [Invitation to the Discord Community](https://discord.gg/etdD3SSJ6T)
2. [GitHub repository of solutions to the problems discussed in the lectures](https://github.com/noc21-cs99/lectures/)
3. [Link to YouTube Playlist for the course](https://www.youtube.com/playlist?list=PLyqSpQzTE6M9p9pKxFGpskf4voY45T2DZ)
:::

::: {.panel-tabset}
## Lectures

::: {#lectures-listing}
:::


## Assignments

<p>These are some practice assignments: the due date is simply the recommended completion deadline. There is no need to submit these assignments.</p>

::: {#assignments-listing}
:::

## Exams

::: {#exams-listing}
:::


:::

:::