---
css: /css/teaching.css
toc: false
sidebar: false
title: ES214. Discrete Mathematics. L02 Quiz.
code-copy: true
---

:::{.column-body-outset}

## ES214. Discrete Mathematics. 

##### L02 Solutions

[Back to the course page](../index.qmd)

:::{.callout-note icon="false"}

# Problem 1. Identify the Circuits

Let $G$ be a simple, undirected, and connected graph. Consider the graphic matroid discussed in class, i.e, where:

- the universe $U$ is the set of _edges_ of $G$, i.e, $E(G)$; 
- the family $\mathcal{F}$ of independent sets is the collection of all subsets of edges that are acyclic.

A _maximal_ independent set in a matroid is called a basis, and for this example, the maximal independent sets correspond to spanning trees.

A _minimal_ dependent set in a matroid is called a circuit. In this example, what are the circuits?

:::


:::{.callout-caution collapse="true" icon="false"} 

# Solution

The circuits of the graphic matroid are the cycles of the graph $G$.

::: 

:::{.callout-note icon="false"}

# Problem 2. Matchings

Let $G$ be a simple, undirected, and connected graph. Consider the following set system:

- the universe $U$ is the set of _edges_ of $G$, i.e, $E(G)$; 
- the family $\mathcal{F}$ of independent sets is the collection of all subsets of edges that are matchings.

Is this a matroid? Why or why not? Justify your answer.

:::



:::{.callout-caution collapse="true" icon="false"} 

# Solution

Not a matroid: consider the graph on the vertex set $\{a,b,c,d\}$ with the edges $\{ab, cd, ad\}$. 

There are two matchings in this instance:

- $M_1 := \{ab,cd\}$ 
- $M_2: \{ad\}$

However, although $|M_1| > |M_2|$, neither of the edges from $M_1$ can be added to $M_2$.

::: 

:::{.callout-note icon="false"}

# Problem 3. Independent Sets

Let $G$ be a simple, undirected, and connected graph. Consider the following set system:

- the universe $U$ is the set of _vertices_ of $G$, i.e, $V(G)$; 
- the family $\mathcal{F}$ of independent sets is the collection of all subsets $S$ of that are independent in $G$, i.e, the subgraph $G[S]$ has no edges.

Is this a matroid? Why or why not? Justify your answer.

:::


:::{.callout-caution collapse="true" icon="false"} 

# Solution

Not a matroid: consider the graph on the vertex set $\{a,b,c\}$ with the edges $\{ab, ac\}$. There are two independent sets: $S_1 := \{b,c\}$ and $M_2: \{a\}$, but neither of the vertices from $S_1$ can be added to $S_2$.

> If the independent sets formed a matroid the problem of finding a maximum independent set would not be NP-complete. {{< bi emoji-smile-upside-down >}} 
>
> --- Comment in class

::: 

:::