---
title: A Primer on Making Personal Websites
css: /css/teaching.css
sidebar: false
toc: false
page-layout: full
---

:::{.column-body-outset}

## A Primer on Making Personal Websites
##### A Workshop

:::{.callout-note collapse="true" icon="false"}

# About the Course


:::

:::{.callout-note collapse="true" icon="false"}
# Logistics

Date: 06 -07 April (Saturday, Sunday) · Time: 10:30 AM - 12:30 PM IST · Venue: 6/201 

:::


:::{.callout-note collapse="true" icon="false"}
# Target Audience
The course material is beginner-friendly: we assume no background in web development.
:::


:::{.callout-note collapse="true" icon="false"}

# Methodology

The course will be taught over Zoom and will involve several hands-on assignments. The course has the following three sections, with two modules in each section:

1.The first section focuses on the various motivations for pursuing research projects, the wrong reasons to take up research, exposure to different research-related careers available.

2.The second section is about the mechanics of getting started with your first research(-ish) project. We introduce some common set of skills every researcher benefits from—taking initiative, reading and writing code, knowing domain-specific tools, parsing papers, communicating over email, and presenting your work. Also learn about the balances you will likely have to strike as you go along, and prepare with us for battles like imposter syndrome or loneliness you may face.

3. The third section covers exploring and approaching research opportunities after having cleared the first two sections. We will have pointers to generic opportunities that you can consider applying to. We will also leave you with suggestions for how to level up from after your first research apprenticeship, including information about preparing for graduate school, and discussions about relevant career options within and beyond academia.
Pre-class reading: Each lecture will have a recommended short video or text we expect students to watch/read before attending class.

Final assessment: The final assessment will involve identifying a project relevant to your interest and skills, and drafting an email expressing your interest in getting started with it.

:::


:::{.callout-note collapse="true" icon="false"}

# Objectives
The course aims to equip students with toolkits to --- (a) determine if research projects are well-aligned with their interests and aspirations, and (b) prepare for relevant research opportunities.
:::


:::{.callout-note collapse="true" icon="false"}

# Outcome
The participants will be well-positioned to determine if a career in research is for them; and if yes, also to find and pursue relevant research opportunities.

:::

### Teaching Plan

---

On the first day, we will go over:

1. Website styles: personal blog, resume, knowledge gardens, etc.
2. Websites we love: case studies
3. Hosting and setup: main options
4. Planning your content
5. Aesthetics
6. Accessibility and Security
7. Auxiliary platforms 

On the second day, we will discuss and get feedback on websites that participants have made.

### Before the Workshop

Answer the following questions:

0. What is the goal of your website? Who is the target audience? What do you think they are looking for?
1. What kind of content would you like to share on your website?
2. What features do you want your website to have?
3. What are some of the websites that you have found useful and think of as model examples for your own?
4. What is your degree of comfort with writing code and basic scripting? 
5. Come up with a basic content plan for your website: what elements will the navigation have, and have a summary of what you want each page to contain.

Please share a Google Doc with answers to these questions by Friday 5PM. This will help me fine-tune to the workshop to your needs.

---




:::