---
css: /css/materials.css
page-layaout: full
title: "Combinatorial Games"
sidebar: true
toc: false
page-navigation: true
---

##### Lecture Notes 
### _on Computational and Combinatorial Aspects of Games_
---

<p>&nbsp;</p>

These are running notes on selected topics in combinatorial games.

I have been developing these as a part of my course on `Computational and Combinatorial Aspects of Games` IIT Gandhinagar. Please see the course websites for additional materials (e.g, problem sets).

At the time of this writing these notes are largely raw and informal, with an emphasis on quick recaps and providing for interactive experiences. They certainly do not substitute --- but hopefully do supplement --- an actual textbook :) I borrow heavily from the following books:

1. [Playing with Discrete Math](http://kyleburke.info/CGTBook.php). This text is appropriate for undergrads who may or may not be math majors.

2. [Games, puzzles and computation](https://www.amazon.in/Games-Puzzles-Computation-Robert-Hearn/dp/1568813228). This text, based on the thesis of Robert A. Hearn, explores computational aspects of games.

If you have any general comments or questions, please leave them below. Thanks!