---
title: "CS607 | Jan-Apr 2024"
sidebar: false
toc: false
css: ../../../css/teaching.css
listing:
  - id: lectures-listing
    contents: materials.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials.ejs
  # - id: assignments-listing
  #   contents: materials-assignments.yml
  #   sort: issueddate asc
  #   page-size: 100
  #   type: table
  #   categories: false
  #   sort-ui: false
  #   filter-ui: false
  #   feed: false
  #   template: ../../materials-assessments.ejs
  #   field-types: 
  #     dateissued: date
  #     due: date
  # - id: quizzes-listing
  #   contents: materials-quizzes.yml
  #   sort: issueddate asc
  #   page-size: 100
  #   type: table
  #   categories: false
  #   sort-ui: false
  #   filter-ui: false
  #   feed: false
  #   template: ../../materials-assessments.ejs
  #   field-types: 
  #     dateissued: date
  #     due: date
  # - id: exams-listing
  #   contents: materials-exams.yml
  #   sort: issueddate asc
  #   page-size: 100
  #   type: table
  #   categories: false
  #   sort-ui: false
  #   filter-ui: false
  #   feed: false
  #   template: ../../materials-assessments.ejs
date-format: DD MMM, YYYY
---


:::{.column-body-outset}

## CS607. Combinatorics with Applications in Computer Science

##### 2024

:::{.callout-note collapse="true" icon="false"}

##### About the Course

<blockquote>
Just as arithmetic deals with integers (with the standard operations), algebra deals with operations in general, analysis deals with functions, geometry deals with rigid shapes, and topology deals with continuity, so does combinatorics deal with configurations. Combinatorics counts, enumerates, examines, and investigates the existence of configurations with certain specified properties. With combinatorics, one looks for their intrinsic properties, and studies transformations of one configuration into another, as well as “subconfigurations” of a given configuration.

<p style="text-align:right;"><em>Claude Berge</em>, Principles of Combinatorics, Dunod, Paris, 1968 (English translation: Academic Press, New York, 1971)</p>
</blockquote>

<blockquote>
Mathematics is the art of reducing any problem to linear algebra.

<p style="text-align:right;"><em>William Stein</em></p>
</blockquote>

This course will delve into some special highlights from the field of combinatorics, with a broad emphasis on applications to computer science. We will frequently encounter the use of linear algebraic methods. We will roughly have four major themes: extremal set systems, randomized algorithms, geometry, graphs. Every now and then, we'll work through "puzzles", which are questions that have a recreational flavor.
:::

:::{.callout-note collapse="true" icon="false"}

##### Target Audience
Did you enjoy Discrete Mathematics? That's a sign: there's a good chance you'll like this too! You might find a slight change of pace and style in the offering, but it will be just as fun and full of awe-inspiring discovery. 

If you haven't done Discrete Mathematics, but you enjoy discret-ey puzzles and questions, you'll probably also like this. 

That said, I am not a recommender algorithm, so please join us for a class or two during the add/drop period to decide if this course is for you :)
:::

:::{.callout-tip collapse="true" icon="false"}

##### Prerequisites

The course is mostly self-contained, but a general degree of comfort with proofs and some elementary linear algebra would be useful.

:::

:::{.callout-tip collapse="true" icon="false"}

##### References

List of References

1. [Thirty-three Miniatures: Mathematical and Algorithmic Applications of Linear Algebra](https://kam.mff.cuni.cz/~matousek/stml-53-matousek-1.pdf) by Jiří Matoušek
2. [Extremal Combinatorics: With Applications in Computer Science](https://www.amazon.in/Extremal-Combinatorics-Applications-Computer-Theoretical/dp/3642173632) (Texts in Theoretical Computer Science. An EATCS Series) by Stasys Jukna

Additional pointers (papers, articles, videos, etc.) specific to each lecture will be provided in the notes.

:::

:::{.callout-caution collapse="true" icon="false"}

##### Timings and Venue

Venue: 7/110

Timings: 15:30 - 16:50 on Mondays and 14:00 - 15:20 on Thursdays.

:::
:::{.callout-caution collapse="true" icon="false"}

##### TAs and Office hours

Office Hours: By email.

TA: Aditi Sethia

:::

:::{.callout-important collapse="true" icon="false"}

##### Evaluation policy

- Each of the three quizzes account for 10% of the grade.
- The midsem exam accounts for 15% of the grade.
- The endsem exam accounts for 20% of the grade.
- There will be worksheets accompanying each lecture, due at midnight on the day of the lecture. Each worksheet is worth two points, and your total points from the worksheets is capped at 35 points, which contributes to 35% of the grade.
:::

:::{.callout-important collapse="true" icon="false"}

##### Logistics

- For IITGN students, (pre-)register through IMS as usual. 
- All quizzes and exams will be on Mathmatize; please [sign up here](https://mathmatize.com/c/753).
- For announcements, please sign up on Google classroom [with this link](https://classroom.google.com/c/NjQ2NjU0ODA2NzA3?cjc=ebtcrf2) or use the invite code **ebtcrf2**.
- If you are not from IITGN and are interested in taking up the course, then please send us an email.

:::

::: {.panel-tabset}

## Lectures

All slides for the initial lectures can be found [here](https://slides.com/neeldhara/CS607-2023).

::: {#lectures-listing}
:::


## Worksheets

Coming Soon.

<!-- ::: {#assignments-listing}
::: -->

## Quizzes

Coming Soon.

<!-- ::: {#quizzes-listing}
::: -->

## Exams

Coming Soon.

<!-- ::: {#exams-listing}
::: -->

:::

:::


