---
title: "Martin Gardner Reading Group | Spring 2024"
sidebar: false
toc: false
css: ../../../css/teaching.css
listing:
  - id: youtube-listing
    contents: youtube.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: materials.ejs
date-format: DD MMM, YYYY
---


:::{.column-body-outset}

## Reading Group on Martin Gardner's Games and Puzzles

#### by Jyothi Krishnan

##### Spring 2024 (Jan/Feb)

:::{.callout-note collapse="true" icon="false"}

##### About the Meetups

This is a reading group based on games and puzzles described by Martin Gardner across his various books and columns. Curated and presented by [Jyothi Krishnan](Jyothi Krishnan).


:::
:::{.callout-note collapse="true" icon="false"}

##### Target Audience
You will find these meetings interesting if any of the following is relatable:

- you enjoy puzzles and/or games
- you are a Martin Gardner fan
- you are generally math-curious

:::

:::{.callout-tip collapse="true" icon="false"}

##### Prerequisites
We make no assumptions, although we appreciate everyone bringing their enthusiasm along :)
:::

:::{.callout-tip collapse="true" icon="false"}

##### References

01. Hexaflexagons And Other Mathematical Diversions · The First Scientific American Book of Mathematical Puzzles and Games by Martin Gardner
02. The Second Scientific American Book Of Mathematical Puzzles And Diversions by Martin Gardner
03. New Mathematical Diversions by Martin Gardner · The Mathematical Association of America (MAA)
04. The Unexpected Hanging And Other Mathematical Diversions · A Classic Collection of Puzzles and Games From Scientific American ·  Martin Gardner
05. The Sixth Book of Mathematical Diversions by Martin Gardner
06. Mathematical Carnival by Martin Gardner · The Mathematical Association of America (MAA)
07. Mathematical Magic Show by Martin Gardner · The Mathematical Association of America (MAA)
08. Mathematical Circus by Martin Gardner · The Mathematical Association of America (MAA)
09. The Magic Numbers of Dr. MATRIX by Martin Gardner · Prometheus Books Buffalo, New York
10. Wheels, Life and Other Mathematical Amusements by Martin Gardner · W. H. Freeman and Company, New York
11. Knotted Doughnuts and Other Mathematical Entertainments by Martin Gardner · W. H. Freeman and Company, New York
12. Penrose Tiles to Trapdoor Ciphers... And the Return of Dr. Matrix by Martin Gardner · The Mathematical Association of America (MAA)
13. Fractal Music Hypercards and More... Mathematical Recreations from SCIENTIFIC AMERICAN Magazine by Martin Gardner
14. The Last Recreations Hydras, Eggs, and Other Mathematical Mystifications · The final collection of Martin Gardner's Mathematical Games column from Scientific American


:::

:::{.callout-tip collapse="true" icon="false"}

##### Materials

Will be updated.

:::
:::{.callout-caution collapse="true" icon="false"}

##### Timings and Venue

We meet at 9PM IST on all weekdays in January except for the third week. Join [via Zoom](https://iitgn-ac-in.zoom.us/j/99224439902?pwd=MERwdENnN0xGTmVwWVlKMkhvVzlJUT09) (Meeting ID: `992 2443 9902`, Passcode: `gardner`) and sign up for reminders below.

:::

---

:::{.callout-note appearance="minimal"}
### Sign Up for Reminders

If you are a calendar person, you can use [this link](https://calendar.google.com/calendar/u/0?cid=Y183NzZmMmMwMWUwMDAyNDhmODZhNWFmNjA3MWMwYjA3Mjk3ZmM1YWY1MTUxODBjY2ZhZjRmYTkzZjY3NTk5ODgyQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) to add all events to your Google Calendar. This requires you to be signed in. Otherwise, you can sign up for daily reminders at 7PM using the form below.

<br>

<iframe
scrolling="no"
style="width:100%!important;height:220px;border:1px #ccc solid !important"
src="https://buttondown.email/2024-MGRG?as_embed=true"
></iframe><br /><br />

:::

:::{.callout-tip appearance="minimal"}
_Acknowledgements._ This reading group is led by Jyothi: many thanks to her for volunteering the idea and her time!
:::

:::{.callout-caution appearance="minimal"}
_Note._ Topics are tentative and subject to change. Links to recordings will be added below as we go along.
:::

::: {#youtube-listing}
:::

:::