---
title: "About Exportober"
date: "2021-09-24"
categories: [exportober]
fields: [date, title]
page-layout:  full
toc: true
---

::: {.grid}

::: {.g-col-6}
In a massively impulsive move nudged by some Twitter feedback, I recently launched [the Exportober challenge](../2021/).

The TL;DR version:

- Put up a **piece of content*** everyday between 27th September and 30th October, with the possibility of skipping one day per week;
- Post a link to your content on Twitter with #exportober
- That's it, actually. 🤷‍♀️
:::

::: {.g-col-6}
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Anyone else procrastinating on starting a blog, CS or otherwise? Would you be interested in being held mutually accountable for a few weeks to overcome the initial inertia? <br><br>Do let me know! I’ll try to setup something systematic-looking if there’s interest 🙂</p>&mdash; Neeldhara (@neeldhara) <a href="https://twitter.com/neeldhara/status/1439607978445869057?ref_src=twsrc%5Etfw">September 19, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
:::

:::


## What's allowed in #exportober?

I was deliberately vague about the terms-and-conditions that goes with the piece of content piece above. The rules I mentioned were minimal: since there are no restrictions of age, keep the content SFW and generally legal. Other than that, anything goes, for example:

- Can I doodle? Yes.
- Can I meme? Yes.
- Can I make a comic? Yes.
- Can I quip? Yes.
- Can I tweet a thread? Yes.
- Can I tweet a single tweet? Yes.
- Can I song and/or hum and/or dance? Yes.
- Can I react? I am unfamiliar with this genre, but yeah, why not?
- Can I just quote? Uhh, ok-fine, sure — maybe be sure to include a reaction?
- Can I commit? Yes, please! Oh, you mean — can it be a GitHub commit? Right, yeah, sure.


:::{.column-margin}
<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">One a day is a lot! (Unless tweets count). I used to blog regularly but not even one a week at its peak, I think.</p>&mdash; Rahul Siddharthan (@rsidd120) <a href="https://twitter.com/rsidd120/status/1440537832980828165?ref_src=twsrc%5Etfw">September 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
:::

:::{.column-margin}
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">in case anyone is looking for inspiration, in true student fashion, i am already planning on cheating by turning all the math puns i have in mind to comics [&#39;ring arthur and his knights of the round table&#39; but where ring arthur is a noncommutative ring without unity]</p>&mdash; tiiiiredddd (@vuisnotabot) <a href="https://twitter.com/vuisnotabot/status/1440752412298399744?ref_src=twsrc%5Etfw">September 22, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
:::


As you can see, there are no restrictions on format or length or quality. It can be whatever you want, and however long or short you want it to be. The point is to *get into the habit* of putting a bit of yourself into something tangible that you'd want to share.

So while you could technically schedule thirty pieces of Harry Potter trivia in advance — *that* would kind of defeat the purpose.

## Is this for me? #whybother with #exportober

In general, I imagine only you would know if this is for you — this may not be a priority or a point of interest for you right now, but if you're reading this, possibly your interest is at least mildly piqued?

What this is about is setting aside some time for yourself and to participate alongside friends who're in it for fun and profit:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We often avoid taking action because we think &quot;I need to learn more,&quot; but the best way to learn is often by taking action.</p>&mdash; James Clear (@JamesClear) <a href="https://twitter.com/JamesClear/status/1308857494983323650?ref_src=twsrc%5Etfw">September 23, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

- The fun bit is in the making and sharing.
- The profit bit is the hope that we trick ourselves into making this a bit of a regular habit for life.

Longer term, you may or may not want to be sharing or publishing on a daily basis. But hopefully, longer term, **you are engaged with the process on a regular basis**.

Personally, there's almost nothing that I do consistently on a daily basis, not counting the things one needs to do continue being alive. I'd like to see if I can change that a bit^[c.f. the next section for a different perspective.], and apparently doing such things bit by bit — and with some public commitment — [is a good idea](https://jamesclear.com/atomic-habits), hence the micro-nature of the challenge.

<blockquote class="twitter-tweet" data-conversation="none"><p lang="en" dir="ltr">So overall I’ve gotten to a point where I’m just afraid to even think about putting something together because I think it’s an unrealistic commitment of time. <br><br>I’m also really bad at chunking - everything I do of this sort manifests at the wrong end of an all-nighter 🙈</p>&mdash; Neeldhara (@neeldhara) <a href="https://twitter.com/neeldhara/status/1439682627837980675?ref_src=twsrc%5Etfw">September 19, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

## I want to be in, but I stoop no lower than meaningful masterpieces...

Hmm. One way that you could still make this work for you is to build out your masterpiece bit by bit. If it's a tutorial, you could plan it out in advance and work through one coherent section a day. If it's a sketch, you could share your partial progress as you go along, and even put it together in a timelapse at the end? That would be great to see!

There are some types of long-form content that aren't naturally amenable to this type of chunking; say you want to put together a video exposition, make an origami sculpture, or crochet a Klein bottle. In this situation, you could either use the challenge to document your process and progress; or you could just claim to engage in #exportoberlite with a reduced frequency of production — say once a week, or one masterpiece at the end — you'll just have to still tweet it out so I can catalog it ❤️

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I really don’t like the illusion that there is one process for making and that it involves writing every day. Thinking is work to. So is reading. So is doing things that seem unrelated to writing. Our brains are always thinking about what we’re making, whether we’re typing or not</p>&mdash; ChristianAntonGerard (@CAGerardPoet) <a href="https://twitter.com/CAGerardPoet/status/1221128922982690818?ref_src=twsrc%5Etfw">January 25, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Also, while on the subject of masterpieces, there's the [parable of the pots](https://austinkleon.com/2020/12/10/quantity-leads-to-quality-the-origin-of-a-parable/). On the other hand, everyone does have their own process, and the idea isn't to force a format: this process is temporary, flexible, and optional 🙌

## This sounds like fun, but I have no idea what to make.

Oooh. Maybe just ping on Twitter if you are in this situation. I do imagine that there are folks who have more ideas than they can handle, so if you have the bandwidth, it'll even out nicely! For some starter inspiration, just in case it is useful, here are some of the post types that I'm planning for the duration of this challenge, in roughly increasing order of desperation:

1. Trying some of the [Chai and Why? experiments](https://www.tifr.res.in/~outreach/chai_and_why.html) and documenting ~~any accidents~~ learnings.
2. Puzzles and programming contest roundups.
3. Lecture notes for classes/talks I'm teaching and/or attending.
4. Highlights from whatever podcasts I'm tuned into.
5. Clean up draft essays from previous lives.
6. Random doodles. And VSCode keyboard shortcuts.
7. Hot takes on inconsequential debates.^[Let me know if you want prompts.]

I also have a few black holes nurtured over time — I'm looking at you, all my Read-It-~~Never~~Later apps, the starred section in my RSS app, my YouTube watchlist, and relatives. Maybe about time to go down some of these rabbit holes with the excuse of commentary to follow.

So yes, that'll be all for now! Let's see how this goes 🤞 Meanwhile, [please hop on](../2021/) and [spread the word](https://twitter.com/neeldhara/status/1439668714178105347) for all of us? Thank you! 🎉

---

PS. You might be curious about what participating will *look like*. I'm trying to setup a separate page for each participant in the challenge that will pull in all your tagged tweets. I'll share a preview soon!