---
title: CS Research 101 | Shashank Srikant
css: /css/teaching.css
sidebar: false
toc: false
page-layout: full
---

:::{.column-body-outset}

## CS Research 101
##### A Short Course

--- _Shashank Srikant_

:::{.callout-note collapse="true" icon="false"}

# About the Course

When starting off their undergrad degrees in science and engineering, most are fueled by an idealism to do great science. However, no formal resources tell us what research—an established path to great science and engineering—is all about, and how one can get started. As a result, many don’t end up figuring out these details, have no idea what the journey promises to offer, and as a consequence, move on to other well-documented jobs and careers. While there’s nothing wrong with taking up well-documented careers, academia and scholarship loses out on quality talent.

In another extreme, among those few who are exposed to the idea of research while still in undergrad, there exists a frenzy to apply to graduate programs by the end of undergrad. And to achieve this, students tend to optimize working on projects which will land them ‘the best possible’ publications and letters from professors. While few successfully discover their interests this way, it generally fails as an approach.

This course aims to fast-track the process of learning more about research-first graduate programs and/or jobs. It will nudge you to introspect whether problem solving and research is something you will enjoy, and provide some concrete steps for your discovery. It is not designed to merely provide instructions on applying successfully to graduate programs or advanced degrees. Rather, it aims to introduce you to the realities of doing research, which should in turn help you gauge your preparedness for graduate school or a career in research.
:::

:::{.callout-note collapse="true" icon="false"}
# About the Instructor

Shashank is currently a Ph.D. candidate in computer science at the CS & AI Lab (CSAIL), in the department of Electrical engineering and Computer science (EECS) at MIT. He is advised by Una-May O'Reilly. His research interests are at the intersection of machine learning, program analysis, and cognitive neuroscience. He has published his work at top-tier academic venues and has authored multiple patents.

Prior to his Ph.D. studies, he was a senior researcher at Aspiring Minds' research lab, where he helped build, deploy, and manage a number of innovative products involving machine learning. These products are used by >1M job applicants across the world today. In this role, he also helped organize international workshops, led academic collaborations, and helped set up communities in India to participate and engage in ML and data science (http://www.datasciencekids.org, http://ml-india.org).

He is also interested in governance, and science education and policy. To understand the nuances of how state governments deliver benefits to the last-mile, he worked with Seva Setu, an organization which aims to bridge the gap between governments and people, for a year in rural Bihar in India.

Details on his work can be found on [his webpage](https://shashank-srikant.github.io/). 

:::


:::{.callout-note collapse="true" icon="false"}
# Dates and Time

31st October – 5th November • Timing: 6:30PM to 8:30PM • Mode: Online (over Zoom)

:::


:::{.callout-note collapse="true" icon="false"}
# Target Audience
The course material is beginner-friendly: the only pre-requisite is a willingness to commit time and curiosity about research pursuits in computer science (broadly interpreted).

The course is designed for undergraduates in computer science and allied areas in any year looking to plan out their first or second research projects, however, participation is not restricted and all are welcome.
:::


:::{.callout-note collapse="true" icon="false"}

# Methodology

The course will be taught over Zoom and will involve several hands-on assignments. The course has the following three sections, with two modules in each section:

1.The first section focuses on the various motivations for pursuing research projects, the wrong reasons to take up research, exposure to different research-related careers available.

2.The second section is about the mechanics of getting started with your first research(-ish) project. We introduce some common set of skills every researcher benefits from—taking initiative, reading and writing code, knowing domain-specific tools, parsing papers, communicating over email, and presenting your work. Also learn about the balances you will likely have to strike as you go along, and prepare with us for battles like imposter syndrome or loneliness you may face.

3. The third section covers exploring and approaching research opportunities after having cleared the first two sections. We will have pointers to generic opportunities that you can consider applying to. We will also leave you with suggestions for how to level up from after your first research apprenticeship, including information about preparing for graduate school, and discussions about relevant career options within and beyond academia.
Pre-class reading: Each lecture will have a recommended short video or text we expect students to watch/read before attending class.

Final assessment: The final assessment will involve identifying a project relevant to your interest and skills, and drafting an email expressing your interest in getting started with it.

:::


:::{.callout-note collapse="true" icon="false"}

# Objectives
The course aims to equip students with toolkits to --- (a) determine if research projects are well-aligned with their interests and aspirations, and (b) prepare for relevant research opportunities.
:::


:::{.callout-note collapse="true" icon="false"}

# Outcome
The participants will be well-positioned to determine if a career in research is for them; and if yes, also to find and pursue relevant research opportunities.

:::

### Teaching Plan

---

Course materials also available [from here](https://csresearch101.netlify.app).

|Topics | Resources |
|---	  |---        |
|Day 1: Motivation::Module 1 - Why research?     | [[Notes]](m1.qmd), [[Survey]](https://forms.gle/Fq1pQsRxSFkxR3scA), [[Youtube]](https://www.youtube.com/watch?v=p1KMy1LJPZ4), [[Slides]](https://slides.com/neeldhara/csresearch101-p1)|
|Day 2: Motivation::Module 2 - The fundamentals  | [[Notes]](m2.qmd), [[Reading: Taking initative]](https://researchtopracticeconnections.wordpress.com/2015/09/02/how-not-to-suck-at-taking-initiative/), [[Youtube]](https://www.youtube.com/watch?v=2R8iM7cg_1g), [[Slides]](https://slides.com/neeldhara/csresearch101-p2) |
|Day 3: Mechanics::Module 3 - Skills 1   	| [[Notes]](m3.qmd), [[Reading: Working with a professor]](https://www.cs.jhu.edu/~jason/advice/how-to-work-with-a-professor.html), [[Youtube]](https://www.youtube.com/watch?v=g6ty9x_FeuM), [[Slides]](https://slides.com/neeldhara/csresearch101-p3)|
|Day 4: Mechanics::Module 4 - Skills 2   	|  [[Notes]](m4.qmd), [[Reading: Writing emails]](https://vanschneider.com/blog/how-to-email-a-busy-person/), [[Youtube]](https://www.youtube.com/watch?v=ur0en59J_9s), [[Slides]](https://slides.com/neeldhara/csresearch101-p4)|
|Day 5: Begin journey::Module 5 - Next steps |  [[Notes]](m5.qmd), [[Reading: CS PhD application FAQs]](https://parentheticallyspeaking.org/articles/us-cs-phd-faq/), [[Youtube]](https://www.youtube.com/watch?v=lWcew1hw9JU), [[Slides]](https://slides.com/neeldhara/csresearch101-p5)|
|Day 5: Begin journey::Module 6 - Resources | [[Notes]](m6.qmd) |


### Homework

---

1. Share the URL to your webpage.

    If you do not have a webpage, make a simple one on Github pages. 
    Let the page just have your name: there's no need to fill it with any content.
    See <a href="https://csresearch101.netlify.app/m3.html#pre-requisite-have-a-webpage">the corresponding course webpage</a> for relevant resources to get started with Github pages.

2. Mention the names and web URLs of 3 professors in India who you think do interesting work. Importantly, for each professor you list, mention in 1-2 sentences why you selected them. This may be informed by your romantic notion of interests in a few areas of CS -- that's okay.

3. Pick one paper authored by any one professor you listed in (2) that they have published in the last five years.
What area of computer science is this paper from? 

4. Where was this paper published? Mention the venue and year.

5. Read the abstract of this paper and describe in 3-4 sentences your understanding of what the paper achieves. 
You do not have to read the whole paper. Attempt to just understand broadly what the paper achieves.

6. Ask one question about this paper. 
This may have been answered in the paper---you do not have to read and understand the whole paper to see if they have already answered it. 
We want you to demonstrate that you have thought about the content of the paper.

7. Use <a href="https://csrankings.org/">CS Rankings</a> to find out the top publishing venues in the area the paper you read belongs to (e.g. databases, machine vision, etc.).

8. Using CS Rankings, find out the best venues in the following fields of computer science:

    - Computer architecture
    - Human-computer interface
    - Graphics and computational geometry
    - Computing education

    See <a href="https://csresearch101.netlify.app/m6.html#experiences-of-researchers">this section</a> in Module 6 of our course webpage for a list of popular areas in computer science. 
    
    For each area listed, we also document a researcher's journey who specializes in that area.

9. Write out an email to this professor expressing an interest in working on a project related to this paper.
<b>**Do not send this email to the professor. Just share the draft of this email with us.**</b>
You can assume you have already done 1-2 relevant projects and courses even if you haven't--it's fine to reference these fictitious experiences in your email to make a case for yourself.

~~Submit your <a href="https://forms.gle/kNMTX2a6HfBoqZ9k7">responses here</a>.~~


:::