---
title: Fundamentals of Science Communication | Siddharth Kankaria
css: /css/teaching.css
sidebar: false
toc: false
---

## Fundamentals of Science Communication
##### A Short Course

--- _Siddharth Kankaria_

:::{.callout-note collapse="true" icon="false"}

# About the Course

Science communication is an act of connecting people with knowledge, emotions and shared experiences within the field of science. It is both an art to be practised creatively as well as a science to be studied systematically. 

This week-long course will provide an introduction to the theory and practice of science communication and outline some fundamental tenets of communicating science strategically. Using interactive approaches like discussions, games, and activities, this course will provide Early Career Researchers with an introduction to the frameworks, formats and importance of science communication, and equip them to design, implement and evaluate their science communication efforts effectively. 

:::

:::{.callout-note collapse="true" icon="false"}
# About the Instructor

Siddharth Kankaria is a science communication practitioner and researcher working at NCBS Bangalore and the Founder of the SciCommSci Club – a flagship initiative for engaging with the science of science communication. He is keenly interested in developing the research-practice continuum within science communication, contributing to mentorship, capacity-building &amp; DEI efforts, and developing intersectional science engagement practices for the Global South. Connect with him on Twitter or LinkedIn at @SiddhrthKnkaria. 

:::


:::{.callout-note collapse="true" icon="false"}
# Dates and Time

25th July to 29th July 2022 • 4PM --- 6PM

:::


:::{.callout-note collapse="true" icon="false"}
# Target Audience

The course material is beginner-friendly and hands-on. The only prerequisite is enthusiasm to learn science communication.
:::


:::{.callout-note collapse="true" icon="false"}

# Methodology

The course will be taught in person and feature in-class practice exercises as well. A collection of resources will be ready for the students’ reference from the first class onwards.
:::


:::{.callout-note collapse="true" icon="false"}

# Objectives
The course aims to introduce the fundamentals of effective science communication.
:::


:::{.callout-note collapse="true" icon="false"}

# Outcome
Participants will have the skills to craft their own science communication pieces and be able to convey their specialized research work in a manner that is accessible and interesting to a non-specialist, broad audience.

:::

### Teaching Plan

---

Day 1

- Defining SciComm &amp; Public Engagement
- SciComm Strategy &amp; Fundamentals
- Exercise: Choose a SC &amp; PE project and develop a strategy zine for it

Day 2

- History of Science Communication
- SciComm Models
- Exercise: Write a 200 word piece describing a suitable model for your SC &amp; PE project

Day 3

- Importance of Narratives for SciComm + Storytelling techniques for SciComm
- Dealing with Jargon + Metaphors &amp; Analogies + Balancing Accuracy vs. Accessibility
- Exercise: Storyboarding a concept for your SC &amp; PE project

Day 4

- Ethics of doing SciComm
- Understanding your SciComm Audiences
- Exercise: Write a 300-word profile of a specific target audience for your SC &amp; PE activity 

Day 5

- Exercise: Present your SC &amp; PE project overview with reflections from course modules 
- Challenges of doing SciComm in India
- Building a SciComm Career in India