---
title: Visual Science Communication | Ipsa Jain
css: /css/teaching.css
sidebar: false
toc: false
---

## Visual Science Communication
##### A Short Course

--- _Dr Ipsa Jain_

:::{.callout-note collapse="true" icon="false"}
# About the Course

Science can be communicated to a target audience through different avenues including written, visual, audio, and a combination thereof. The use of visual communication through art and illustrations, video, audio-visual content and more, has been noted to have a wider reach and breach new barriers. 

Through this two-day course, students will engage with science communication through images. They will be introduced to some fundamentals of visual science communication, understand how to tell stories using images, learn to tailor their content to different target audiences, and gain perspectives on how different visual language can impact science communication. 
:::

:::{.callout-note collapse="true" icon="false"}
# About the Instructor
Ipsa Jain is a scientist turned illustrator, who uses the visual medium to tell tales of science. She makes images, zines, and books among other things. Her latest book, co-authored with Minhaj Sirajuddin, called Actually, Colors Speak is about coloration in the animal kingdom. 

She is a Visual Communication faculty at Srishti Manipal Institute, Bangalore. She has collaborated with various institutes like Centre for Cellular and Molecular Biology (CCMB), inStem (CCMB), Azim Premji University and more on projects that centred around science illustrations, video, and sci-art. She also does independent work under the moniker ipsawonders. She works and lives in Bangalore. 

To know more about her work visit ipsawonders.com or connect with her through Twitter, Linkedin, Instagram or email: ipsajain.31@gmail.com 
:::


:::{.callout-note collapse="true" icon="false"}
# Dates and Time

Tentative dates: 5th November and 6th November

Timing: 11 am to 1:00 pm  •  lunch break • 2:30pm to 4:00 pm •  tea break •  4:30 pm to
6:00 pm
:::


:::{.callout-note collapse="true" icon="false"}
# Target Audience
The course material is beginner-friendly with ample exercises. The only prerequisite is enthusiasm to learn science communication through art.

:::


:::{.callout-note collapse="true" icon="false"}

# Methodology

The course will be taught in person and will feature in-class practice exercises as well. The sessions will be interactive with lots of drawing (without judgement on skill levels) and peer discussions and critique sessions.
:::


:::{.callout-note collapse="true" icon="false"}

# Objectives
The course aims to help students build conceptual frameworks to understand, appreciate, and critique images in science.
:::


:::{.callout-note collapse="true" icon="false"}

# Outcome
The participants can develop their unique style of science communication and engage with subject matters in a more creative and unencumbered manner. The course will help them develop and polish their ideas for various visual science communication efforts.

:::

### Teaching Plan

---

Day 1: Images in science

- Classification and classical examples
- Scientific progress from observational drawings (Haeckel’s images, personal work)
- Transformation of images, meaning making, storytelling (DNA story or Darwin story)

Day 2: Visual Science communication

- Mediums, audiences, intent-content-context bridges
- Comparing visual media for similar content made for different audiences
- Clarity vs complexity in scientific work
- Group activity based on give brief, followed by peer review