---
title: "CS 699 | Summer 2023"
sidebar: false
toc: false
css: ../../../css/teaching.css
listing:
  - id: youtube-listing
    contents: youtube.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: materials.ejs
date-format: DD MMM, YYYY
---


:::{.column-body-outset}

## Reading Group on Combinatorial and Computational Aspects of Games

##### Summer 2023

:::{.callout-note collapse="true" icon="false"}

##### About the Course

We are going to play some games! Here are some typical questions we will explore:

- Who is going to win assuming optimal play?
- What is the complexity of determining the winner (or a winning strategy) given the rules of a game?

If you are curious about how this typically goes, start with the excellent talks [here](https://www.youtube.com/watch?v=846A4rgO_os) and [here](https://www.youtube.com/watch?v=gxIz1hYgzoM).

If you want to play: here's [Subtraction](https://subtraction.netlify.app/), and here's [Sim](https://gameofsim.neeldhara.repl.co). 

This is an informal summer reading group.

:::
:::{.callout-note collapse="true" icon="false"}

##### Target Audience
You will find this course interesting if:

- you enjoy playing games,
- you enjoy logic puzzles [like this one](https://www.youtube.com/watch?v=LKvjIsyYng8) or probability puzzles [like this one](https://www.youtube.com/watch?v=6_yU9eJ0NxA), or
- you like [box-stacking challenges](https://en.wikipedia.org/wiki/Instant_Insanity).

:::

:::{.callout-tip collapse="true" icon="false"}

##### Prerequisites
This course is self-contained and involves no pre-requisites.
:::

:::{.callout-tip collapse="true" icon="false"}

##### References

1. [Winning Ways for your Mathematical Plays](https://en.wikipedia.org/wiki/Winning_Ways_for_Your_Mathematical_Plays), the classic book that is an amazing ride through all parts of CGT.
2. [Lessons in Play](http://www.cs.otago.ac.nz/lessonsinplay/), an excellent text for upper level undergrads and grad students in math.
3. [Combinatorial Game Theory](https://www.ams.org/books/gsm/146/), a great text for advanced mathematicians.
4. [Playing with Discrete Math](http://kyleburke.info/CGTBook.php). This text is appropriate for undergrads who may or may not be math majors.
5. [Games, puzzles and computation](https://www.amazon.in/Games-Puzzles-Computation-Robert-Hearn/dp/1568813228). This text, based on the thesis of Robert A. Hearn, explores computational aspects of games.
6. [Is NP-hard](https://www.isnphard.com/), a compendium of games with a lot of information about their complexity status.
7. [Math Games with Bad Drawings](https://www.amazon.com/Math-Games-Bad-Drawings-Games-ebook/dp/B09BN43BP4), another compendium of games, with --- as the title suggestions --- bad drawings and lots of trivia.

Note. The descriptions for the first four books are borrowed from the [Sprouts 2023](http://kyleburke.info/sprouts/sprouts2023/) website.

:::
:::{.callout-caution collapse="true" icon="false"}

##### Timings and Venue

- Venue: Online
- Lectures: Everyday at 11AM

:::

<!-- :::{.callout-important collapse="true" icon="false"}

##### Evaluation policy
- Develop your own game and demonstrate a non-trivial analysis X 1 = 15 points
- Develop new results about the complexity of an existing game = 15 points
- Implement a known game in as an interactive JS application X 3 = 30 points
- Three take-home exams = 45 points
- Total capped at 100.

The use of assistance from tools like chatGPT or similar is permitted for the development of the interactive experiences.
:::

:::{.callout-important collapse="true" icon="false"}

##### Register

- For IITGN students, (pre-)register through IMS as usual. 
- Otherwise, please send me an email.

::: -->

Note: We stopped recording after a couple of weeks, however, the topics pursued are listed for the record :) Some initial notes --- to be developed further --- are [here](../../../../materials/games/impartial-games/game-trees/). The handwritten slides from the videos are not currently available.

::: {#youtube-listing}
:::

:::