---
title: "Exportober 2022"
date: "2022-10-07"
categories: [exportober]
fields: [date, title]
page-layout:  full
toc: true
---

## The Leaderboard

<iframe class="airtable-embed" src="https://airtable.com/embed/shrjgp87jlNqDMCy4?backgroundColor=yellow&viewControls=on" frameborder="0" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;"></iframe>

## The Tweets

<iframe class="airtable-embed" src="https://airtable.com/embed/shrwXyP8mGB3KH86i?backgroundColor=yellow&viewControls=on" frameborder="0" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;"></iframe>

## What was this about again?

You can find the original announcement [here](../2022/) and more specifics clarifying the format (or the lack of it) [here](../about/). Here's the short version:

- Put up a piece of content everyday between 1st October and 30th October, with the possibility of skipping one day per week;
- Post a link to your content on Twitter with #exportober
- That's it, actually. 🤷‍♀️

Psst. It's quite fine to sign up even if you're reading this after the 1st of October. The automated tracking exercise here will stop after the 15th of November, so you can be a part of this by just contributing in this window. It certainly does't *have* to be daily and it doesn't *have* to be 30 things, although I found those to be useful default targets to work with for myself.

<!-- ## Sign up! -->

<!-- While I'm not going to write a Twitter bot that will send you daily reminders over DM, I do hope to create a separate page for each registered participant at the end of the challenge that shows off just their entries in one place, so it's helpful to know who you are 😀 -->