---
title: "Applications of Linear Algebra | Summer 2024"
sidebar: false
toc: false
css: ../../../css/teaching.css
listing:
  - id: lectures-listing
    contents: materials.yml
    sort: date asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials.ejs
  - id: assignments-listing
    contents: materials-assignments.yml
    sort: issueddate asc
    page-size: 100
    type: table
    categories: false
    sort-ui: false
    filter-ui: false
    feed: false
    template: ../../materials-assessments.ejs
    field-types: 
      dateissued: date
      due: date
date-format: DD MMM, YYYY
---


:::{.column-body-outset}

## Applications of Linear Algebra

##### Summer 2024

:::{.callout-note collapse="true" icon="false"}

##### About the Course

This course explores applications of tools from linear algebra in combinatorics, geometry, algorithms, and graph theory. We will emphasize proofs and proof techniques. The goal is to use the applications as a backdrop to practice and review linear algebra skills, but also to develop a an understanding of new proof techniques and recognize how to apply them in new settings as well.

:::

:::{.callout-note collapse="true" icon="false"}

##### Target Audience

Logsitically, this course is a special summer offering meant for advanced students of the IITM online BS program in Data Science and undergraduate students of IIT Gandhinagar. Anyone with a background in linear algebra and an interest in the material is welcome to follow along.

:::

:::{.callout-tip collapse="true" icon="false"}

##### Prerequisites
A little linear algerba won't hurt. Try starting here if you have never encountered linear algebra concepts before:

1. [The Linear Algebra course on Khan Academy](https://www.khanacademy.org/math/linear-algebra)
2. [The 3blue1brown Playlist](https://www.youtube.com/watch?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&v=fNk_zzaMoSs&embeds_referring_euri=https://linearalgebra33.discourse.group/&source_ve_path=MjM4NTE) on the "Essence of Linear Algebra"
3. [An interactive introduction](https://brilliant.org/landing/interactive-courses-learn-linear-algebra/) from Brilliant.

:::

:::{.callout-tip collapse="true" icon="false"}

##### References

We will closely follow [Thirty-three Miniatures: Mathematical and Algorithmic Applications of Linear Algebra](https://kam.mff.cuni.cz/~matousek/stml-53-matousek-1.pdf). Additional pointers to tangents and related material will be listed on the individual notes pages.

:::

:::{.callout-tip collapse="true" icon="false"}

##### Materials

Class recordings and slides will be shared on this website as we go along.
Notes will be made available on a best-effort basis.

:::

:::{.callout-tip collapse="true" icon="false"}

##### Grading Policy

- The pre-requisite assignment does not contribute to the course grade.
- The assignments are worth 30% of the final grade (best 3 out of 4, 10% each).
- The course project is a visualization-based programming project worth 15% of the final grade.
- The midsem exam is worth 15% of the final grade.
- The midsem exam is worth 30% of the final grade.

:::

:::{.callout-caution collapse="true" icon="false"}

##### Timings and Venue

- The lectures will be held between 4PM and 6PM on the indicated dates.
- The venue will be announced shortly.
- The course is hybrid, and students who are joining us remotely can attend classes in real-time over Zoom.
- The Zoom link will be shared over email with registered participants.
- The video recordings of the classes will be made available on this website as we go along.

:::



::: {.panel-tabset}

## Lectures

::: {#lectures-listing}
:::


## Assignments


::: {#assignments-listing}
:::


:::

:::