---
title: A nano-course in modern cryptography

css: /css/teaching.css
sidebar: false
toc: false
---

## A nano-course in modern cryptography
##### A Short Course

--- _Prof. Venkata Koppula, IIT Delhi_

:::{.callout-note collapse="false" icon="false"}
# About the Course

While cryptography has been around for centuries, since the middle of twentieth century, cryptography has gradually moved from 'art' to 'science'. Today, most cryptographic primitives/protocols come with a formal security proof. In this lecture series, we will discuss how to define security for cryptographic primitives, followed by constructions, security proofs (and vulnerabilities in real-world cryptosystems). 
:::

:::{.callout-note collapse="false" icon="false"}
# About the Instructor
Venkata Koppula is an Assistant Professor at IIT Delhi. His primary area of research is theoretical cryptography.
:::


:::{.callout-note collapse="false" icon="false"}
# Dates and Time
- Dates: 21-26 December
- Format: Hybrid (over Zoom and at 7/101)
- Time: 5-6:30pm
:::


:::{.callout-note collapse="false" icon="false"}
# Target Audience
Anyone with interest in theoretical computer science is welcome to attend. No cryptography background will be assumed. 
:::

:::{.callout-caution appearance="minimal"}
Join us on Zoom! Use [this link](https://iitgn-ac-in.zoom.us/j/99455739745?pwd=QU9vcWRsbkZMWmdTWFg0RVQxWGp0QT09) with the following details.

- Meeting ID: 994 5573 9745
- Passcode: 007700
:::

<iframe data-tally-src="https://tally.so/embed/3N7GXQ?alignLeft=1&hideTitle=1&transparentBackground=1&dynamicHeight=1" loading="lazy" width="100%" height="214" frameborder="0" marginheight="0" marginwidth="0" title="CRYPTO Course Sign Up"></iframe><script>var d=document,w="https://tally.so/widgets/embed.js",v=function(){"undefined"!=typeof Tally?Tally.loadEmbeds():d.querySelectorAll("iframe[data-tally-src]:not([src])").forEach((function(e){e.src=e.dataset.tallySrc}))};if("undefined"!=typeof Tally)v();else if(d.querySelector('script[src="'+w+'"]')==null){var s=d.createElement("script");s.src=w,s.onload=v,s.onerror=v,d.body.appendChild(s);}</script>

### Teaching Plan

---


:::{.callout-tip appearance="minimal" icon="false"}
**Lecture 1: How to define security?**

We will start with the most basic security setting: Alice and Bob share a secret key, and want to use this secret key for exchanging information securely. The cryptographic primitive that is used for this is called private-key encryption. In this first lecture, we will build towards a popular security definition (called security against 'chosen plaintext attacks') for private key encryption.

<a href="04-CRYPTO/L1-slides.pdf"><span class="bi bi-file-earmark-slides" data-bs-toggle="tooltip" data-bs-placement="top" title="Slides"></span></a> · <a href="https://youtube.com/live/vIKXvEGLOJc?feature=share"><span class="bi bi-film" data-bs-toggle="tooltip"  data-bs-placement="top" title="Video"></span></a> · <a href="../../blog/crypto-intro/index.qmd"><span class="bi bi-journal-richtext" data-bs-toggle="tooltip" s data-bs-placement="top" title="Quick Summary"></span></a>
:::

:::{.callout-note collapse="true" icon="false"}
# Lecture 1 Assignments

1. Show that any correct encryption scheme with perfect one-time security must have key space at least as large as the message space. 

2. In the first lecture, we discussed one-time perfect security. This definition aims to capture the intuition that the adversary does not learn anything about the message if the scheme is one-time perfectly secure. 

   Suppose an encryption scheme is one-time perfectly secure. Show that no adversary, given an encryption of a uniformly random message (using a uniformly random key), can compute the parity of the message bits (with probability 1). You can assume the message space is $n$-bit strings. 

:::


:::{.callout-tip appearance="minimal" icon="false"}
**Lecture 2: The first construction Part I**

In this lecture, we will discuss how to build a private-key encryption scheme secure against chosen-plaintext attacks. We will then discuss how to optimise the ciphertext size (without compromising on security). We will conclude this lecture with a popular cryptographic standard (PKCS v1.5) which was proposed and implemented in the 90s.

<a href="04-CRYPTO/L2-slides.pdf"><span class="bi bi-file-earmark-slides" data-bs-toggle="tooltip" data-bs-placement="top" title="Slides"></span></a> · <a href="https://youtube.com/live/i6BNTPqVF9E?feature=share"><span class="bi bi-film" data-bs-toggle="tooltip"  data-bs-placement="top" title="Video"></span></a> · <a href="../../blog/crypto-intro/index.qmd"><span class="bi bi-journal-richtext" data-bs-toggle="tooltip" s data-bs-placement="top" title="Quick Summary"></span></a>
:::

:::{.callout-tip appearance="minimal" icon="false"}
**Lecture 3: The first construction Part II**

In this lecture, we will discuss how to build a private-key encryption scheme secure against chosen-plaintext attacks. We will then discuss how to optimise the ciphertext size (without compromising on security). We will conclude this lecture with a popular cryptographic standard (PKCS v1.5) which was proposed and implemented in the 90s.

<a href="04-CRYPTO/L3-slides.pdf"><span class="bi bi-file-earmark-slides" data-bs-toggle="tooltip" data-bs-placement="top" title="Slides"></span></a> · <a href="https://youtube.com/live/eE-6W5l2q3U?feature=share"><span class="bi bi-film" data-bs-toggle="tooltip"  data-bs-placement="top" title="Video"></span></a> · <a href="../../blog/crypto-intro/index.qmd"><span class="bi bi-journal-richtext" data-bs-toggle="tooltip" s data-bs-placement="top" title="Quick Summary"></span></a>
:::



:::{.callout-tip appearance="minimal" icon="false"}
**Lecture 4: The need for stronger security**

While the PKCS v1.5 satisfies security against 'chosen-plaintext attacks', it turns out that this security is not enough for the real-world! We will start this lecture with an attack on the PKCS v1.5 scheme, then discuss a stronger definition (called security against 'chosen ciphertext attacks'). This is now the 'gold standard' security definition for encryption schemes. In order to achieve this security, we require a new cryptographic primitive called 'message authentication codes'. We will define and build message auth. codes. Next, we will see how to use message authentication codes to achieve security against chosen-ciphertext attacks.

<a href="04-CRYPTO/L4-slides.pdf"><span class="bi bi-file-earmark-slides" data-bs-toggle="tooltip" data-bs-placement="top" title="Slides"></span></a> · <a href="#"><span class="bi bi-film" data-bs-toggle="tooltip"  data-bs-placement="top" title="Video"></span></a> · <a href="../../blog/crypto-intro/index.qmd"><span class="bi bi-journal-richtext" data-bs-toggle="tooltip" s data-bs-placement="top" title="Quick Summary"></span></a>
:::


:::{.callout-tip appearance="minimal" icon="false"}
**Lecture 5: Public key encryption**

One of the biggest innovations in the area of cryptography is the advent of public key cryptography. In this lecture, we will discuss some background on public key cryptography, followed by a construction for public key encryption.

<a href="04-CRYPTO/L5-slides.pdf"><span class="bi bi-file-earmark-slides" data-bs-toggle="tooltip" data-bs-placement="top" title="Slides"></span></a> · <a href="#"><span class="bi bi-film" data-bs-toggle="tooltip"  data-bs-placement="top" title="Video"></span></a> · <a href="../../blog/crypto-intro/index.qmd"><span class="bi bi-journal-richtext" data-bs-toggle="tooltip" s data-bs-placement="top" title="Quick Summary"></span></a>
:::


:::{.callout-tip appearance="minimal" icon="false"}
**Lecture 6: Digital signatures**

Digital signatures are an essential component in the public key infrastructure. We will discuss their role in public key infrastructure, as well as their importance as a standalone primitive). We will conclude this lecture with a construction of a digital signature scheme. 

<a href="04-CRYPTO/L6-slides.pdf"><span class="bi bi-file-earmark-slides" data-bs-toggle="tooltip" data-bs-placement="top" title="Slides"></span></a> · <a href="#"><span class="bi bi-film" data-bs-toggle="tooltip"  data-bs-placement="top" title="Video"></span></a> · <a href="../../blog/crypto-intro/index.qmd"><span class="bi bi-journal-richtext" data-bs-toggle="tooltip" s data-bs-placement="top" title="Quick Summary"></span></a>
:::

